import { build } from "esbuild";
import { mkdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outfile = resolve(root, "dist/index.js");

mkdirSync(dirname(outfile), { recursive: true });

await build({
  entryPoints: [resolve(root, "src/index.js")],
  outfile,
  bundle: true,
  platform: "node",
  // GitHub's `runs.using: node20` executes dist/index.js directly, so the
  // output must be CommonJS regardless of the source module system.
  format: "cjs",
  target: "node20",
  minify: false,
  sourcemap: false,
  legalComments: "none",
  banner: {
    js: [
      "// reliastra-action v1.0.0",
      "// Generated by `npm run build` from src/ -- do not edit by hand.",
      "// Edit src/, rebuild, and commit dist/ together.",
    ].join("\n"),
  },
});

const bytes = statSync(outfile).size;

// The root package.json declares `"type": "module"` so that src/ can use ESM.
// esbuild emits CommonJS because GitHub's `runs.using: node20` executes
// dist/index.js as CJS. Without this file, Node would read the root
// `"type": "module"` and refuse the CJS bundle in a local checkout, while the
// runner (which has no package.json there) would work. That asymmetry makes
// local test runs lie. Pinning the module system inside dist/ makes local and
// runner behaviour identical.
writeFileSync(
  resolve(root, "dist/package.json"),
  `${JSON.stringify(
    {
      type: "commonjs",
      // Marks the artifact as build output. Keeps `npm publish` from ever
      // shipping dist/ to a consumer's registry.
      private: true,
    },
    null,
    2,
  )}\n`,
);

console.log(`dist/index.js  ${(bytes / 1024).toFixed(1)} KiB`);